### ISSUE TITLE
Question regarding NDA documents but published code

### ISSUE THREAD

**Issue by phlash** [silver-sat/Avionics_Software#401]
Hi SilverSat team - I'm Phil, part of the UK/EU FUNcube team. We're planning on working in the open for our next project and would be interested to know how you are able to publish code that communicates with hardware for which the API documents are under NDA (since the code documents the API by example)?

Many thanks, Phlash.

**Comment by lcongdon** [comment]
Phil, we recommend you confer with your vendors and if necessary legal experts in your country/countries.
